Repository Igor-Kholupko/coop-test, pull requests merged in 2019-03, with the labels that each got.

#27 Update a
  a
Labels: bug

#30 wefwef
  README.md
Labels: enhancement

#42 MeetY-Greeceman colloborator
  Y-Greeceman
Labels: good first issue
